### ISSUE TITLE
About stdi attach & follow-up work

### ISSUE THREAD

**Issue by ttyS0** [jekkos/urjtag-st7xxx#2]
I wanna unbrick an STb7100 board.
This is my connecting gram from [tjtag-arduino](https://github.com/zoobab/tjtag-arduino).
![Connecting gram](https://github.com/zoobab/tjtag-arduino/blob/master/tjtag3-0-1_JTMOD/arduino/arduiggler_schematic.png)

Open the compiled urjtag, following the steps in README.
Two questions about tapmux after having loaded stdi file:

1. `tapmux bypass 1`
Outputs many blank lines.
2. `tapmux stdi attach`
Outputs following

> urj_tap_capture_ir: Invalid state: 88
> urj_tap_defer_shift_register: Invalid state: 8
> loaded overlay boot/init to st40
> hudi_stdi_service_asemode :: data = 00000000
> hudi_stdi_service_asemode :: data = 00000000
> hudi_stdi_service_asemode :: not yet!
> loaded overlay boot/reset to st40
> hudi_stdi_interrupt_target :: not yet!
> hudi_stdi_init_asemode :: not yet!
> hudi_stdi_wait_asemode :: not yet!

**Working fine or going wrong?**

And **another question** for follow-up work:
After the steps in README are done, is it the time to use ST40 Micro Toolset?
I couldn't find a Linux version for the toolset, while I find **devkit** in STLinux 2.4 but executables like sh4tp are missing. So I guess it's not in the STLinux. Could you help me? Thanks for patience :)

**Comment by jekkos** [comment]
think the output here says that something isn't right. 

Does your detect give an idcode as output? You need to use some files from ST40 toolset with urjtag here indeed, they have some binaries that have peek/poke functionality that you will need to read / write from memory. Their paths are in the Readme instructions. Of course after that you will need to write to the flash using poke functionality a uboot image or sth that will allow you to boot it back again

The initial idea with ftd2xx is that you can make ST toolset recognize any ftdi 2xxx (like bus blaster) by changing vid/pid as their genuine expensive adapter so that you can use it with their set of tools.. this could be easier in the end. Don't think you'll be able to use st toolset with arduino. 

Once you have the adapter recognized by st toolset you could eg load uboot into ram using one of their gdb scripts and then rewrite flash using it's interactive console


might be easier in the end to try

**Comment by jekkos** [comment]
Actually this patch is more of a reimplementation of what is already in st toolkit.. there should be a linux version of st toolkit at least, I found one when I was playing with it. I think the issue in my case was that jtag was disabled on the board so I couldn't even get it into debug mode.

**Comment by maxy1** [comment]
HI, Thank you very much for your reply. yes I was able to get it connected
using ftdi mini adapter..  But I'm not sure what command I should use to
dump the memory.  And I think the adapter recognized by st toolset coz my
windows pc installed all the ST drivers. So now I am not sure what command
I should use to read the memory?
Can you pls help me.

Thank you

**Comment by maxy1** [comment]
Thank you. I'm using the Windows version of the st tool kit.

Any idea what commend should I use to read the memory ?

**Comment by jekkos** [comment]
Ok from there on it should be rather straightforward, you can find quite a lot of information on scripts to run from the [avi-plus forum here](http://www.avi-plus.com/repair-tips-forum/miscellaneous-software/others/st40-stb71xx-jtag-interfacing/page-16.html).

There you can see quite some cases in which they used st40 toolkit to debrick using gdb and stmc.

**Comment by jekkos** [comment]
If you read through you will see which files you might need to modify, first try to run one of the default scripts to see if it works. Maybe you will have a different flash chip for which you need to add some JEDEC id's in flash.c file somewhere.. but should be rather clear from reading the posts and looking at the attached source examples

**Comment by ttyS0** [comment]
@jekkos "detect" gives out the id, while the following line is an error message that it's unable to find MANUFACTURERS file. I don't know whether the error will interrupt the process of "detect".

Actually, I'm using FT232R instead of FT2232 or FT4232, which cannot be used for JTAG.
It can be also modified to pretend a STMCL. But I think it cannot be recognized with ST Toolset while it unsupports JTAG.
So the only solution for me is FT232R + Arduino.

**Comment by jekkos** [comment]
Yes maybe you need to define the idcode in manufacturers so that it knows what parts it contains.

should be sufficient to have it recognized as ft2232. The urjtag patch here might be a bit harder to use as once you have the overlays loaded you still need to initialize some registers before you can actually read / write to flash (in this case CE for that).

the python scripts in st toolset might contain this code but then you'll need a way to apply it to urjtag (or execute them manually manually)

**Comment by ttyS0** [comment]
@jekkos 
I found many scripts in a folder called "stdcmd", but mind was refused with these files.
And I'd like to ask that there is no possibilies for FT232R to clone an STMC, right?
If so, I'm determined to buy an FT2232H, which should solve the problem.
Thanks for your patient instruction.
If possible, after I found the way to unbrick my board in Arduino way, I'll share it. :D
